"""add notes field to tasks

Revision ID: 95169ebc696f
Revises: cbb4c1ac631d
Create Date: 2026-02-11 20:32:44.582981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95169ebc696f'
down_revision: Union[str, Sequence[str], None] = 'cbb4c1ac631d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'notes')
    # ### end Alembic commands ###
